#24
Error in indicator: java.lang.ArrayIndexOutOfBoundsException @
com.dukascopy.api.impl.TaLibIndicator.calculate(TaLibIndicator.java:379)
null: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at
com.dukascopy.api.impl.TaLibMetaData.callFunc(TaLibMetaData.java:830)
        at
com.dukascopy.api.impl.TaLibIndicator.calculate(TaLibIndicator.java:379)
        at
com.dukascopy.api.impl.Indicators$IndicatorCalc.calculateIndicator(Indicators.java:6216)
        at
com.dukascopy.api.impl.Indicators$IndicatorCalc.performIndicatorCalculation(Indicators.java:6152)
        at
com.dukascopy.api.impl.Indicators$IndicatorCalc.calculate(Indicators.java:6079)
        at
com.dukascopy.api.impl.Indicators.calculateIndicator(Indicators.java:4261)
        at
com.dukascopy.dds2.greed.agent.strategy.tester.TesterIndicators.calculateIndicator(TesterIndicators.java:27)
        at
com.dukascopy.api.impl.Indicators.function(Indicators.java:4247)
        at com.dukascopy.api.impl.Indicators.macd(Indicators.java:2441)
        at
hu.fnf.devel.forex.criteria.MACDCloseCriterion.calc(MACDCloseCriterion.java:77)
        at
hu.fnf.devel.forex.utils.CloseCriterionDecorator.calcProbability(CloseCriterionDecorator.java:25)
        at
hu.fnf.devel.forex.states.SignalSeekerState.getSignal(SignalSeekerState.java:54)
        at hu.fnf.devel.forex.StateMachine.onTick(StateMachine.java:441)
        at
com.dukascopy.dds2.greed.agent.strategy.tester.AbstractStrategyRunner.historicalTickReceived(AbstractStrategyRunner.java:361)
        at
com.dukascopy.dds2.greed.agent.strategy.tester.StrategyRunner.run(StrategyRunner.java:359)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at com.tictactec.ta.lib.Core.TA_INT_MACD(Core.java:15887)
        at com.tictactec.ta.lib.Core.macd(Core.java:15790)
        at
com.tictactec.ta.lib.CoreAnnotated.macd(CoreAnnotated.java:5567)
        ... 19 more
com.dukascopy.api.JFException: Error during buy calculation.
        at
hu.fnf.devel.forex.criteria.MACDCloseCriterion.calc(MACDCloseCriterion.java:85)
        at
hu.fnf.devel.forex.utils.CloseCriterionDecorator.calcProbability(CloseCriterionDecorator.java:25)
        at
hu.fnf.devel.forex.states.SignalSeekerState.getSignal(SignalSeekerState.java:54)
        at hu.fnf.devel.forex.StateMachine.onTick(StateMachine.java:441)
        at
com.dukascopy.dds2.greed.agent.strategy.tester.AbstractStrategyRunner.historicalTickReceived(AbstractStrategyRunner.java:361)
        at
com.dukascopy.dds2.greed.agent.strategy.tester.StrategyRunner.run(StrategyRunner.java:359)
        at java.lang.Thread.run(Thread.java:744)
Caused by: com.dukascopy.api.JFException:
java.lang.reflect.InvocationTargetException
        at
com.dukascopy.api.impl.Indicators$IndicatorCalc.calculateIndicator(Indicators.java:6223)
        at
com.dukascopy.api.impl.Indicators$IndicatorCalc.performIndicatorCalculation(Indicators.java:6152)
        at
com.dukascopy.api.impl.Indicators$IndicatorCalc.calculate(Indicators.java:6079)
        at
com.dukascopy.api.impl.Indicators.calculateIndicator(Indicators.java:4261)
        at
com.dukascopy.dds2.greed.agent.strategy.tester.TesterIndicators.calculateIndicator(TesterIndicators.java:27)
        at
com.dukascopy.api.impl.Indicators.function(Indicators.java:4247)